package nl.ou.fresnelforms.fresneltowiki;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

import org.apache.commons.lang3.StringEscapeUtils;

/**
 * Represents a wiki page.
 * 
 * @author Joop
 *
 */
public class Article {

	private static final String XML_HEADER_1 = "<page>\n" + " <title>";
	private static final String XML_HEADER_2 = "</title>\n" + " <revision>\n" + " <timestamp>";
	private static final String XML_HEADER_3 = "</timestamp>\n" + " <contributor>\n"
			+ "  <username>Fresnel Forms generation</username>\n" + "  <id>1</id>\n" + " </contributor>\n"
			+ " <comment>generated by Fresnel Forms on Protégé</comment>\n" + "  <text xml:space='preserve'>";
	private static final String XML_FOOTER = "\n  </text>\n </revision>\n</page>";

	private String content = null;
	private String title = null;

	/**
	 * The constructor.
	 * 
	 * @param title page title
	 * @param content page content
	 */
	public Article(String title, String content) {
		this.title = title;
		this.content = content;
	}

	private String currentTime() {
		Date rawDate = Calendar.getInstance().getTime();
		String iso8601time = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssXXX").format(rawDate);
		return iso8601time;
	}

	/**
	 * Getter for content.
	 * 
	 * @return content of the page
	 */
	public String getContent() {
		return content;
	}

	/**
	 * Getter for title.
	 * 
	 * @return title of the page
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * Getter for xmlPage.
	 * 
	 * @return page XML-packed
	 */
	public String getXMLPage() {
		return XML_HEADER_1 + StringEscapeUtils.escapeXml10(title) + XML_HEADER_2 + currentTime() + XML_HEADER_3
				+ StringEscapeUtils.escapeXml10(content) + XML_FOOTER;
	}

}
